name: pirec
version: 0.0.0
author: Szumi Xie <szumixie@gmail.com>
github: szumixie/pirec

extra-doc-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-export-lists
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wmissing-deriving-strategies
  - -Wprepositive-qualified-module

  - -Wno-name-shadowing
  - -fplugin=Control.Effect.Plugin

default-extensions:
  - RecursiveDo
  - NoImplicitPrelude
  - TupleSections
  - LambdaCase
  - EmptyCase
  - MultiWayIf
  - BlockArguments
  - ImportQualifiedPost

  - TypeOperators
  - LiberalTypeSynonyms
  - ExistentialQuantification
  - GADTs
  - TypeFamilyDependencies
  - DataKinds
  - PolyKinds
  - StandaloneKindSignatures
  - TypeApplications
  - RankNTypes
  - RoleAnnotations

  - DuplicateRecordFields
  - NamedFieldPuns

  - EmptyDataDeriving
  - StandaloneDeriving
  - DeriveTraversable
  - DeriveGeneric
  - GeneralisedNewtypeDeriving
  - DeriveAnyClass
  - DerivingVia

  - ViewPatterns
  - PatternSynonyms

  - FlexibleContexts
  - DefaultSignatures
  - FunctionalDependencies
  - FlexibleInstances
  - UndecidableInstances
  - InstanceSigs

  - NegativeLiterals
  - BinaryLiterals
  - HexFloatLiterals
  - NumDecimals
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedLabels

  - ConstraintKinds
  - QuantifiedConstraints

  - AllowAmbiguousTypes
  - ScopedTypeVariables
  - PartialTypeSignatures
  - NamedWildCards

  - TemplateHaskell

  - BangPatterns
  - StrictData

dependencies:
  - base
  - relude

  - these
  - semialign

  - text-short
  - vector
  - hashtables

  - optics
  - these-optics

  - mtl
  - transformers
  - in-other-words
  - in-other-words-plugin

  - with-utf8
  - optparse-applicative

  - prettyprinter
  - megaparsec

_no-paths: &no-paths
  condition: false
  other-modules: Paths_pirec

_exe-options: &exe-options
  main: Main.hs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - pirec

library:
  source-dirs: src
  when:
    - *no-paths
    - condition: flag(release)
      ghc-options:
        - -Wunused-packages

executables:
  pirec:
    source-dirs: app
    <<: *exe-options
    when:
      - *no-paths

tests:
  test-pirec:
    source-dirs: test
    <<: *exe-options
    when:
      - *no-paths
      - condition: true
        dependencies:
          - hspec
          - hspec-discover
          - hspec-hedgehog
          - hedgehog

benchmarks:
  bench-pirec:
    source-dirs: benchmark
    <<: *exe-options
    when:
      - *no-paths
      - condition: true
        dependencies:
          - criterion

flags:
  release:
    manual: true
    default: false
  dump:
    manual: true
    default: false

when:
  - condition: flag(release)
    ghc-options:
      - -O2
      - -funbox-strict-fields
  - condition: "!flag(release)"
    dependencies:
      - pretty-simple
  - condition: flag(dump)
    ghc-options:
      - -ddump-to-file
      - -dumpdir=.dumps
      - -ddump-simpl
      - -ddump-hi

      - -dppr-case-as-let
      - -dsuppress-uniques
      - -dsuppress-idinfo
      - -dsuppress-module-prefixes
      - -dsuppress-type-applications
      - -dsuppress-coercions
