resolver: lts-18.17
packages:
  - .
extra-deps:
  - relude-1.0.0.1

  - optics-0.4
  - optics-core-0.4
  - optics-extra-0.4
  - optics-th-0.4

  - in-other-words-0.2.1.0
  - in-other-words-plugin-0.1.0.0
