resolver: lts-17.5
packages:
  - .
extra-deps:
  - optics-0.4
  - optics-core-0.4
  - optics-extra-0.4
  - optics-th-0.4
  - indexed-traversable-instances-0.1

  - in-other-words-0.2.0.0
  - in-other-words-plugin-0.1.0.0
